- client/screens/WelcomeScreen.js
use native wind (tailwind) instead of react native stylesheets for styling.
> use nativewind for styling

- client/screens/HomeScreen.js
- client/screens/LoginScreen.js
- client/screens/WelcomeScreen.js
> add basic buttons and texts and placeholders

- client/screens/TieBreakerScreen.js
add some basic styles to tie breaker page and do some design changes
> add basic style for tie breaker page

- client/screens/GameRoomScreen.js
add some basic buttons and input fields and texts to create the wireframe
> add some basic buttons and input fields and texts

- client/screens/ActivitiesScreen.js
add basic components to create the wireframe
> add basic components to create the wireframe

- server/__tests__/foods.test.js
- server/app.js
- server/controllers/foods-controller.js
- server/listen.js
- server/package-lock.json
- server/package.json
Adds testing and listen.js, as well as updates package.json with test scripts
> Jn 02 foods tests

- client/babel.config.js
- client/firebase.js
- client/package-lock.json
- client/package.json
- client/screens/LoginScreen.js
linked login/registration with firebase auth system
> linked login/registration with firebase auth system

- server/__tests__/couples.test.js
- server/controllers/couples-controller.js
- server/models/couples-model.js
- server/routes/couples.js
Implemented GET, POST, and DELETE API routes to interact with a MongoDB database, enabling the management of couples data.
> create couples route, db, controller, model and tests for GET POST DELETE

- client/App.js
- client/firebase.js
- client/package-lock.json
- client/package.json
- client/screens/HomeScreen.js
- client/screens/LoginScreen.js
added bottom tabs navigation + persistent login
> Fe work on bottom tabs navigation + persistent login

- client/screens/HomeScreen.js
- client/screens/WelcomeScreen.js
add a temporary log out button to test login functionality
> add a temporary log out button to test login functionality

- client/App.js
- client/screens/ActivitiesScreen.js
- client/screens/HomeScreen.js
- client/screens/LoginScreen.js
- client/screens/TieBreakerScreen.js
- client/screens/WelcomeScreen.js
> Fe styling appbar

- client/App.js
- client/screens/ActivitiesScreen.js
- client/screens/LoginScreen.js
- client/screens/TieBreakerScreen.js
- client/screens/WelcomeScreen.js
Styled welcome page more, now with navigateable buttons.
bottom tab icons are all there now with animations and transitions.
added serach query to filter out data on activities page
added some backgrounds colour to buttons with a bit of transparent to make it standout more.
> Fe styling all pages

- server/endpoints.json
- server/routes/api.js
connected /api with endpoints.json to act as a landing page
> connected /api with endpoints.json to act as a landing page

- client/api.js
- client/screens/LoginScreen.js
- client/screens/WelcomeScreen.js
> Fe connect login with backend

- client/App.js
- client/api.js
- client/screens/LoginScreen.js
- client/screens/WelcomeScreen.js
add login condition and confirmation condition + username display
> add login condition and confirmation condition + username display

- client/components/ForgotPasswordModal/ForgotPasswordModal.js
- client/components/NavigationModal/NavigationModal.js
- client/screens/InspirationScreen.js
- client/screens/UserProfileScreen.js
added on press back drop to modals + removed minus buttons from inspiration screen
> added on press back drop to modals + removed minus buttons from inspiration screen

- client/screens/InspirationScreen.js
add search functionality to inspiration screen similar to activity category screen + add isLoading functionality to inspiration screen
> add search functionality to inspiration screen similar to activity category screen + add isLoading functionality to inspiration screen

- client/api.js
- client/components/AddTvShowsForm.js
- client/screens/ActivitiesScreen.js
> add tv shows form

- client/api.js
- client/components/AddFoodsForm.js
- client/screens/ActivitiesScreen.js
> add foods form

- client/components/AddActivityForm.js
- client/components/AddFoodsForm.js
- client/components/AddMoviesForm.js
- client/components/AddTvShowsForm.js
- client/screens/ActivitiesScreen.js
add navigations between forms and fix styling issue + switch to use react-native-modal package instead of native react's modal
> add navigations between forms and fix styling issue

- client/screens/ActivitiesScreen.js
- client/screens/InspirationScreen.js
fix search functionality due to mismatch names on activity page and inspiration page. removed some comments as well.
> fix search functionality due to mismatch names
